language: android
android:
  components:
    - build-tools-29.0.2
    - android-28
    - extra

before_install:
  - chmod +x gradlew

git:
  depth: 3

script:
  - ./TeamCode/src/main/java/org/firstinspires/ftc/teamcode/rework/Tests/MathFunctionsTest.java